multiply files better support

diff --git a/tests/test_sh-tools-rc b/tests/test_sh-tools-rc
--- a/tests/test_sh-tools-rc
+++ b/tests/test_sh-tools-rc
@@ -9,21 +9,17 @@ source $src_dir/sh-tools-rc
 
 printf "\nCurrent directory: $PWD\n"
 
-cd $tests_dir
+cd $tests_dir || return 1
 
-local download_dir=$PWD/test_sh-tools-output-3sc8dc45
+local download_dir=$PWD/test_sh-tools-output-$(date +%s)
 
-local out_file=$download_dir/$src_file
-
-curl_github 'krallin/tini' 'v0.18.0' $download_dir "ddist.sh src/tini.c"
+curl_github 'krallin/tini' 'v0.18.0' $download_dir ddist.sh src/tini.c
 
 ! [[ -f "$download_dir/ddist.sh" ]] &&\
-    printf "\nTest fail: File 'ddist.sh' Not found\n" &&\
-    return 1
+    printf "\nTest fail: File 'ddist.sh' Not found\n"
 
 ! [[ -f "$download_dir/tini.c" ]] &&\
-    printf "\nTest fail: File 'tini.c' Not found\n" &&\
-    return 1
+    printf "\nTest fail: File 'tini.c' Not found\n"
 
 rm -rf "$download_dir"
 
